[package]
name = "xtra"
version = "0.3.0-alpha"
description = "A tiny actor framework"
authors = ["Restioson <restiosondev@gmail.com>"]
edition = "2018"
license = "MPL-2.0"
repository = "https://github.com/Restioson/xtra"
documentation = "https://docs.rs/xtra"
readme = "README.md"
keywords = ["async", "actor", "futures", "tokio", "async-std"]

[dependencies]
flume = { git = "https://github.com/zesterer/flume", default-features = false, features = ["async"] }
floom_async = { path = "./floom_async" }
futures = { version = "^0.3" }
tokio = { version = "^0.2", features = ["rt-core", "time"], optional = true }
async-std = { version = "^1", features = ["unstable"], optional = true }

[dev-dependencies]
num_cpus = "^1"

[features]
with-tokio-0_2 = ["tokio"]
with-async_std-1 = ["async-std"]

[[example]]
name = "basic_tokio"
path = "examples/basic_tokio.rs"
required-features = ["with-tokio-0_2", "tokio/full"]

[[example]]
name = "basic_tokio_async"
path = "examples/basic_tokio_async.rs"
required-features = ["with-tokio-0_2", "tokio/full"]

[[example]]
name = "basic_async_std"
path = "examples/basic_async_std.rs"
required-features = ["with-async_std-1", "async-std/attributes"]

[[example]]
name = "basic_async_std_async"
path = "examples/basic_async_std_async.rs"
required-features = ["with-async_std-1", "async-std/attributes"]

[[example]]
name = "crude_bench"
path = "examples/crude_bench.rs"
required-features = ["with-tokio-0_2", "tokio/full"]
